### PR TITLE
Create Code of conduct

### PR DESCRIPTION
**Pull request by flor14**
I selected some ideas from other CoCs to start writing RepoHack' CoC. Please, be free to modify or continue with this file if you want.
Best
Florencia

### CODE REVIEW

**Comment by annakrystalli** [comment]
Thank you so much @flor14 !  This is a great start and the community managers code of ethics is a good find! I'm actually thinking whether that section might actually be more relevant for event organisers, in which case there could be a section especially for them?

**Comment by annakrystalli** [comment]
I really like the Galaxy CoC that @orchid00 posted in the issue too (https://github.com/galaxyproject/training-material/blob/master/CODE_OF_CONDUCT.md). I'm thinking there are aspects of that that could be useful for the participants section.

**Comment by flor14** [comment]
Yes, I agree it is good! because also it is more general, so can be used in
events and social media both.
What is the idea now, just to adopt it or select the parts we like and
modify them in our own version?

**Comment by annakrystalli** [comment]
I reckon we can adapt it. For thu I think we are covered by the Carpentry CoC and some extra points I make in the slides.

Which I have now finished!! (sorry I hadn't responded early but I was finalizing the rest of the materials)

Feel free to review and feed back if you have some time! https://github.com/reprohack/reprohack-2019-06-27

Everything should be self-explanatory in the README and if not, please let me know what you think is missing! (an issue would be fine) :)

**Comment by flor14** [comment]
I read everything and I found it great.
I like that you add a link with an example of an answer to the author. +1
Also seems everything very complete, full of links. Congrats Anna!

I hope everything goes well tomorrow.

PS: Not sure if it is a Disney one, but my favorite character is SpongeBob
SquarePants

**Comment by annakrystalli** [comment]
Thank you sooooooooooo much for reviewing and all your help so far! Will be more responsive after this week so we can continue our CoC discussions. I'll try and get some photos and tweet them out! In the mean time, feel free to say hello in the gitter channel :)

**Comment by annakrystalli** [comment]
Closing as dealt with in #25

**Pull request closed without merging**
